---
  - name: write swappiness config file
    action: template src=templates/swappiness.conf.j2 dest=/etc/sysctl.d/swappiness.conf mode=0644

  - name: get swappiness value
    action: command cat /proc/sys/vm/swappiness
    register: actual_swappiness

  - name: set swappiness value to "$swappiness"
    action: command "sysctl" "vm.swappiness=$swappiness"
    when_integer: "${actual_swappiness.stdout} != $swappiness"
    notify:
      - swapoff
      - swapon
